// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDj0ez5g3dks_KHSz4c2dE5lKQbh2NUec',
    appId: '1:1045392461328:web:db2586dad043e4bd364495',
    messagingSenderId: '1045392461328',
    projectId: 'basvi-b87a5',
    authDomain: 'basvi-b87a5.firebaseapp.com',
    storageBucket: 'basvi-b87a5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1mXrmTFqyItHU_kjlvAjBz7DTeObVhGk',
    appId: '1:408327570230:android:2b221d9841942842d2a997',
    messagingSenderId: '408327570230',
    projectId: 'mi-primer-proyecto-ace72',
    databaseURL: 'https://mi-primer-proyecto-ace72-default-rtdb.firebaseio.com',
    storageBucket: 'mi-primer-proyecto-ace72.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwT07zBaVEqMtFVodp3VwQz6RGGTAQdwQ',
    appId: '1:1045392461328:ios:7c7eca454819130a364495',
    messagingSenderId: '1045392461328',
    projectId: 'basvi-b87a5',
    storageBucket: 'basvi-b87a5.firebasestorage.app',
    iosBundleId: 'com.example.basvi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwT07zBaVEqMtFVodp3VwQz6RGGTAQdwQ',
    appId: '1:1045392461328:ios:7c7eca454819130a364495',
    messagingSenderId: '1045392461328',
    projectId: 'basvi-b87a5',
    storageBucket: 'basvi-b87a5.firebasestorage.app',
    iosBundleId: 'com.example.basvi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDj0ez5g3dks_KHSz4c2dE5lKQbh2NUec',
    appId: '1:1045392461328:web:c8d590791d9895d4364495',
    messagingSenderId: '1045392461328',
    projectId: 'basvi-b87a5',
    authDomain: 'basvi-b87a5.firebaseapp.com',
    storageBucket: 'basvi-b87a5.firebasestorage.app',
  );
}
