name: CI BASVI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Configurar Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.44.2'
          channel: 'stable'

      - name: Instalar dependencias
        run: flutter pub get

      - name: Analizar código
        run: flutter analyze

      - name: Ejecutar pruebas
        run: flutter test

      - name: Construir APK
        run: flutter build apk --debug

      - name: Guardar APK como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: basvi-apk
          path: build/app/outputs/flutter-apk/app-debug.apk
